extends BaseWidgetNode
class_name NetworkWidgetNode


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	var label = get_node("Label")
	var label_text: String = ''
	for address in IP.get_local_addresses():
		label_text += address + '\n'
	label.text = label_text


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	var label = get_node("Label")
	var label_text: String = ''
	for address in IP.get_local_addresses():
		label_text += address + '\n'
	label.text = label_text
